export const medicalSpecialties = [
    "Cardiology",
    "Dermatology",
    "Endocrinology",
    "Gastroenterology",
    "Hematology",
    "Infectious Disease",
    "Internal Medicine",
    "Nephrology",
    "Neurology",
    "Obstetrics and Gynecology",
    "Ophthalmology",
    "Orthopedics",
    "Otolaryngology (ENT)",
    "Pediatrics",
    "Physical Medicine and Rehabilitation",
    "Pulmonology",
    "Psychiatry",
    "Radiology",
    "Rheumatology",
    "Surgery",
    "Urology",
    "Dentist",
  ];


  export const searchkeywords = [
    "जुकाम (Jukam)",
    "दमा (Dama)",
    "निमोनिया (Nimonिया)",
    "अवसाद (Avsaad)",
    "मिर्गी (Mirgi)",
    "फ्लू (Flu)",
    "पार्किंसंस रोग (Parkinson Rog)",
    "मलेरिया (Malaria)",
    "अल्जाइमर रोग (Alzeimer Rog)",
    "तपेदिक (T.B)",
    "स्ट्रोक (Stroke)",
    "मधुमेह (Madhumeh)",
    "डेंगू बुखार (Dengue Bukhar)",
    "हाई ब्लड प्रेशर (High Blood Pressure)",
    "हाई कोलेस्ट्रॉल (High Cholesterol)",
    "ऑस्टियोपोरोसिस (Osteoporosis)",
    "आंखों की बीमारी (Aankhon ki Bimari)",
    "कानों की बीमारी (Kaanon ki Bimari)",
    "त्वचा रोग (Twacha Rog)",
    "हृदय रोग (Hriday Rog)",
    "पीलिया(Hepatitis)",
    "कुपोषण(Malnutrition)",
    "किडनी रोग (Kidney Rog)",
    "लिवर रोग (Liver Rog)",
    "कैंसर (Cancer)",
  
  ]